Import('mainEnv')
buildEnv = mainEnv.Clone()


lib_target = 'cstore'
lib_sources = ['chunkstore.cc', 'chunkserver.cc', 'registry.cc', 'registryserver.cc']

buildEnv.Append(CPPPATH = ['#rpc', '#'])

chunkstoreLibrary = buildEnv.StaticLibrary(target = lib_target, source = lib_sources)
Return('chunkstoreLibrary')
