import os
import sys
import string
from unit_test import runUnitTests
sys.path.append('%s/library' % (Dir('#').abspath))

Import('mainEnv', 'testEnv')
configEnv = mainEnv.Clone()
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('mfsLibrary')
Import('commonLibrary')
Import('chunkstoreLibrary')
Import('rpcLibrary')
depLibs = [mfsLibrary, fscLibrary, rpcLibrary, chunkstoreLibrary, commonLibrary]

test = myTestEnv.Program('test', source = [Glob('*.test.cxx'), Glob('*.fixture.cxx'), Glob('*.helper.cxx'), 'main.cxx'], LIBS=['UnitTest++', 'pthread', 'rt']+depLibs)
runtests = myTestEnv.Command("test.passed", ['test', mfsLibrary], runUnitTests)

myTestEnv.addUnitTestSuite(test[0].path, 'SuiteRadixTree')
myTestEnv.addUnitTestSuite(test[0].path, 'SuitePInode')
myTestEnv.addUnitTestSuite(test[0].path, 'SuiteHashTableEntry')
myTestEnv.addUnitTestSuite(test[0].path, 'SuiteHashTablePage')
myTestEnv.addUnitTestSuite(test[0].path, 'SuiteHashTableBucket')
myTestEnv.addUnitTestSuite(test[0].path, 'SuiteHashTable')
#myTestEnv.addUnitTest(test[0].path, 'SuitePInode', 'TestWriteReadBlock3')
