import os
import sys
import string
import testfw
import copy
from integration_test import runIntegrationTests

Import('mainEnv', 'testEnv')
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('fssLibrary')
Import('mfsLibrary')
Import('commonLibrary')
Import('chunkstoreLibrary')
Import('rpcLibrary')
depLibs = [mfsLibrary, fscLibrary, rpcLibrary, chunkstoreLibrary, commonLibrary]
serverDepLibs = [fssLibrary, rpcLibrary, chunkstoreLibrary, commonLibrary]
objects = myTestEnv['OBJECTS']

testProgram = myTestEnv.Program('test', source = [Glob('*.test.cc'), Glob('*.fixture.cc'), Glob('*.helper.cc'), objects], LIBS=['UnitTest++', 'pthread', 'rt']+depLibs)
serverProgram = myTestEnv.Program('smain', source = myTestEnv['SERVER_OBJECTS'], LIBS=['pthread', 'rt']+serverDepLibs)
runtests = myTestEnv.Command("test.passed", ['test', fscLibrary], runIntegrationTests)


###############################################################################
# INTEGRATION TEST SCHEDULES
############################################################################### 

myTestEnv.addIntegrationTest(testfw.integration_test.IntegrationTest(
    name = 'RPC:TestServerIsAlive',
    init_script = None,
    testfw = testProgram, server = serverProgram,
    clients = { 
        'C1': ( testProgram, [('T1', 'RPC:TestServerIsAlive')])
    },
    rendezvous = []
))
