Import('buildEnv')
Import('bcsClientLibrary')
Import('osdClientLibrary')
Import('scmLibrary')
Import('commonLibrary')

libLocalBuildEnv = buildEnv.Clone()
localBuildEnv = buildEnv.Clone()

lib_target = 'cfsc'
lib_sources = [
               'c_api.cc', 
               'client.cc', 
               'file.cc',
	      ]

cfscLibrary = libLocalBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)
cfs_lib_objs = libLocalBuildEnv.Object(lib_sources)

# Be careful with linkage order for static libraries
localBuildEnv.Append(LIBS = cfscLibrary)
localBuildEnv.Append(LIBS = bcsClientLibrary)
localBuildEnv.Append(LIBS = osdClientLibrary)
localBuildEnv.Append(LIBS = scmLibrary)
localBuildEnv.Append(LIBS = commonLibrary)
localBuildEnv.Append(LIBS = ['pthread', 'rt'])
localBuildEnv.Program('cfsclient', ['main.cc']) 

Return('cfscLibrary', 'cfs_lib_objs')
