import os
import re
import sys
import string
import testfw
import copy
from integration_test import runIntegrationTests
#sys.path.append('%s/test/integration/ssa' % (Dir('#').abspath))

Import('mainEnv', 'testEnv')
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('fssLibrary')
Import('mfsClientLibrary')
Import('mfsServerLibrary')
Import('commonLibrary')
Import('spaLibrary')
Import('bcsClientLibrary')
Import('bcsServerLibrary')
Import('ssaClientLibrary')
Import('ssaServerLibrary')
clientDepLibs = [mfsClientLibrary, fscLibrary, bcsClientLibrary, ssaClientLibrary, spaLibrary, commonLibrary]
serverDepLibs = [mfsServerLibrary, fssLibrary, bcsServerLibrary, ssaServerLibrary, spaLibrary, commonLibrary]
objects = myTestEnv['OBJECTS']

serverProgram = myTestEnv.Program('smain', \
	source = myTestEnv['SERVER_OBJECTS'], LIBS=['pthread', 'rt']+serverDepLibs)
testProgram = myTestEnv.Program('test', \
	source = [Glob('*.test.cc'), Glob('*.fixture.cc'), Glob('*.helper.cc'), \
                  Glob('*/*.test.cc'), Glob('*/*.fixture.cc'), Glob('*/*.helper.cc'), objects], \
	LIBS=['UnitTest++', 'pthread', 'rt']+clientDepLibs)
runtests = myTestEnv.Command("test.passed", ['test', fscLibrary], runIntegrationTests)



###############################################################################
# INTEGRATION TEST SCHEDULES
############################################################################### 



import test.integration.ssa.lock
import test.integration.ssa.hlock
import test.integration.ssa.stm
import test.integration.ssa.registry
import test.integration.ssa.storage
import test.integration.ssa.obj

test.integration.ssa.lock.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.ssa.hlock.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.ssa.stm.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.ssa.registry.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.ssa.storage.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.ssa.obj.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
