Import('mainEnv')
Import('rpcLibrary')
Import('chunkstoreLibrary')
Import('lockservLibrary')
Import('commonLibrary')
Import('v6fsLibrary')

buildEnv = mainEnv.Clone()


lib_target = 'fsc'
lib_sources = ['extent.cc', 'namespace.cc', 'nameservice.cc']
fscLibrary = buildEnv.StaticLibrary(target = lib_target, source = lib_sources)

buildEnv.Append(CPPPATH = ['#rpc', '#'])
buildEnv.Append(LIBS = fscLibrary)
buildEnv.Append(LIBS = rpcLibrary)
buildEnv.Append(LIBS = chunkstoreLibrary)
buildEnv.Append(LIBS = lockservLibrary)
buildEnv.Append(LIBS = v6fsLibrary)
buildEnv.Append(LIBS = commonLibrary)
buildEnv.Append(LIBS = ['pthread', 'rt'])
buildEnv.Program('fsclient', ['main.cc']) 
