Import('mainEnv')
Import('rpcLibrary')
Import('chunkstoreLibrary')
Import('lockservLibrary')
Import('commonLibrary')
#Import('v6fsLibrary')
Import('mfsLibrary')

buildEnv = mainEnv.Clone()
libBuildEnv = mainEnv.Clone()

buildEnv.Append(CPPPATH = ['#rpc', '#'])
libBuildEnv.Append(CPPPATH = ['#rpc', '#'])

lib_target = 'fsc'
lib_sources = ['client.cc', 'c_api.cc', 'extent.cc', 'namespace.cc', 'mpinode.cc']
lib_sources += ['smgr.cc']
lib_sources += ['imgr.cc', 'icache.cc']
lib_sources += ['fdmgr.cc']
lib_sources += ['file.cc']
fscLibrary = libBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)

# Be careful with linkage order for static libraries
buildEnv.Append(LIBS = mfsLibrary)
buildEnv.Append(LIBS = fscLibrary)
buildEnv.Append(LIBS = rpcLibrary)
buildEnv.Append(LIBS = chunkstoreLibrary)
buildEnv.Append(LIBS = lockservLibrary)
#buildEnv.Append(LIBS = v6fsLibrary)
buildEnv.Append(LIBS = commonLibrary)
buildEnv.Append(LIBS = ['pthread', 'rt'])
buildEnv.Program('fsclient', ['main.cc']) 

Return('fscLibrary')
