# Configuration file

debug:
{
    # 0 = silent
    level = 0;

    module:
    {
        all = False;
        rpc = False;
        client:
        {
            inode = False;
            name = False;
            lckmgr = False;
            hlckmgr = False;
            omgr = False;
            salloc = False;
        };
        server:
        {
            bcs = False;
            lckmgr = False;
            hlckmgr = False;
            salloc = False;
            storagesystem = False;
        };
    };
};

ipc:
{
    sharedbuffer:
    {
        size = "1M";
    };
};

scmmodel:
{
    # SCM latency in nanoseconds (0 = no emulated latency)
    latency = 0;
}
