from configure import configure
import os, sys
mainEnv = Environment()

configure(mainEnv)

sys.path.append(os.path.join(Dir('#').abspath, 'tool'))

AddOption("--test",
	action="store_true", dest="run_tests",
	default = False,
	help="run tests")

AddOption("--test-integration",
	action="store_true", dest="run_integration_tests",
	default = False,
	help="run integration tests")

AddOption("--test-stdout",
	dest="test_stdout",
	type='string',
	nargs = 1,
	action="store", 
	default = 'none',
	help="Set tests' stdout: none, interactive, buffered")

AddOption("--test-stderr",
	dest="test_stderr",
	type='string',
	nargs = 1,
	action="store", 
	default = 'none',
	help="Set tests' stderr: none, interactive, buffered")

AddOption('--test-filter',
	action="store", dest='test_filter',
	type='string',
	metavar='NAME',
	help='a regular expression used to match tests to run')

mainEnv['TEST_FILTER'] = GetOption('test_filter')
mainEnv['TEST_STDOUT'] = GetOption('test_stdout')
mainEnv['TEST_STDERR'] = GetOption('test_stderr')

#mainEnv.Append(LIBS = ['tcmalloc'])
#mainEnv.Append(LIBS = ['hoard'])
#mainEnv.Append(CCFLAGS=' -g -O2 -Wall')
mainEnv.Append(CCFLAGS=' -g -O2')
#mainEnv.Append(CCFLAGS = '-fno-omit-frame-pointer', LINKFLAGS= '/home/hvolos/workspace/tools/google-perftools-1.7/.libs/libprofiler.so')


if mainEnv['GOOGLE_SPARSEHASH']:
	mainEnv.Append(CPPPATH = [mainEnv['GOOGLE_SPARSEHASH']])


Export('mainEnv')

# Build stuff 
SConscript('src/SConscript', variant_dir = 'build/src')

# Run tests
SConscript('test/SConscript', variant_dir = os.path.join('build/test'))
