import os
import sys
import string
import copy

Import('mainEnv', 'testEnv')
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('mfsClientLibrary')
Import('commonLibrary')
Import('spaLibrary')
Import('ipcClientLibrary')
Import('ssaClientLibrary')
depLibs = [mfsClientLibrary, fscLibrary, ipcClientLibrary, ssaClientLibrary, spaLibrary, commonLibrary]

myTestEnv.Program('namespace', source = [Glob('*.cc')], LIBS=['pthread', 'rt']+depLibs)
