Import('buildEnv')
Import('commonLibrary')

clientBuildEnv = buildEnv.Clone()
serverBuildEnv = buildEnv.Clone()

# client backend

clt_lib_target = 'mfsclt'
clt_lib_sources = []
clt_lib_sources += ['client/dir_inode.cc', 
                    'client/file_inode.cc', 
                    'client/inode_factory.cc', 
                    'client/mfs.cc', 
		    'client/sb_factory.cc'
		   ]

mfsLibrary = clientBuildEnv.SharedLibrary(target = clt_lib_target, source = clt_lib_sources)


# server backend


Return('mfsLibrary')
