import os
import sys
import string
import copy

Import('mainEnv', 'testEnv')
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('mfsClientLibrary')
Import('commonLibrary')
Import('scmLibrary')
Import('bcsClientLibrary')
depLibs = [mfsClientLibrary, fscLibrary, bcsClientLibrary, scmLibrary, commonLibrary]

#myTestEnv.Program('lock_tester', source = [Glob('*.cc')], LIBS=['pthread', 'rt']+depLibs)
