Import('buildEnv')
localBuildEnv = buildEnv.Clone()
lib_sources = []
lib_objects = localBuildEnv.SharedObject(lib_sources)
rpcLibrary = localBuildEnv.SharedLibrary('rpc', lib_objects)
Return('rpcLibrary', 'lib_objects')
