Import('buildEnv')
localBuildEnv = buildEnv.Clone()


lib_target = 'rpc'
lib_sources = ['rpc.cc', 'connection.cc', 'pollmgr.cc', 'thr_pool.cc', 'jsl_log.cc']

rpcLibrary = localBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)
Return('rpcLibrary')
