Import('buildEnv')
localBuildEnv = buildEnv.Clone()

lib_target = 'spa'
lib_sources = [
               'pregion/pregion.cc',
               'pheap/pheap.cc',
               'pheap/vistaheap.c'	       
              ]

pool_user_sources = [
                     'pool/user/pool.cc'
                    ]

pool_kernel_sources = [
                       'pool/kernel/pool.cc'
                      ]

lib_sources += pool_user_sources

spaLibrary = localBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)


localBuildEnv.Program(target = 'tool/pool/pool', source = lib_sources + ['tool/pool/main.cc', 'tool/pool/mkpool.cc'])

Return('spaLibrary')
