Import('mainEnv')
buildEnv = mainEnv.Clone()


lib_target = 'common'
lib_sources = ['pheap.cc', 'vistaheap.c']

buildEnv.Append(CPPPATH = ['#', '#common'])

commonLibrary = buildEnv.StaticLibrary(target = lib_target, source = lib_sources)
Return('commonLibrary')
