Import('buildEnv')
localBuildEnv = buildEnv.Clone()

lib_target = 'sal'
lib_sources = [
               'pregion/pregion.cc',
               'pheap/pheap.cc',
               'pheap/vistaheap.c'	       
              ]

pool_user_sources = [
                     'pool/user/pool.cc'
                    ]

pool_kernel_sources = [
                       'pool/kernel/pool.cc'
                      ]

lib_sources += pool_user_sources

salLibrary = localBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)


Return('salLibrary')
