Import('buildEnv')
localBuildEnv = buildEnv.Clone()

lib_target = 'sal'
lib_sources = [
               'pregion/pregion.cc',
               'pheap/pheap.cc',
               'pheap/vistaheap.c'	       
              ]

salLibrary = localBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)


Return('salLibrary')
