import os
import sys
import string
from unit_test import runUnitTests
sys.path.append('%s/library' % (Dir('#').abspath))

Import('mainEnv', 'testEnv')
configEnv = mainEnv.Clone()
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('mfsLibrary')
Import('commonLibrary')
Import('chunkstoreLibrary')
Import('rpcLibrary')
depLibs = [mfsLibrary, fscLibrary, rpcLibrary, chunkstoreLibrary, commonLibrary]

test = myTestEnv.Program('test', source = [Glob('*.test.cxx'), Glob('*.fixture.cxx'), Glob('*.helper.cxx'), 'main.cxx'], LIBS=['UnitTest++', 'pthread', 'rt']+depLibs)
runtests = myTestEnv.Command("test.passed", ['test', fscLibrary], runUnitTests)

myTestEnv.addUnitTestSuite(test[0].path, 'FileDescriptor')
myTestEnv.addUnitTestSuite(test[0].path, 'File')
