Import('buildEnv')
Import('bcsServerLibrary')
Import('osdServerLibrary')
Import('scmLibrary')
Import('commonLibrary')

localBuildEnv = buildEnv.Clone()
libLocalBuildEnv = buildEnv.Clone()

lib_target = 'kvfss'
lib_sources = [
               'fs.cc',
	       'publisher.cc',
               'server.cc',
	       'session.cc',
	       'subtable.cc',
              ]

kvfssLibrary = libLocalBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)

localBuildEnv.Append(LIBS = kvfssLibrary)
localBuildEnv.Append(LIBS = bcsServerLibrary)
localBuildEnv.Append(LIBS = osdServerLibrary)
localBuildEnv.Append(LIBS = scmLibrary)
localBuildEnv.Append(LIBS = commonLibrary)
localBuildEnv.Append(LIBS = ['pthread', 'rt'])
localBuildEnv.Program('fsserver', ['main.cc']) 

Return('kvfssLibrary')
