Import('buildEnv')
localBuildEnv = buildEnv.Clone()

lib_target = 'scm'
lib_sources = [
               'scm/memcpy.cc',
	       'pregion/pregion.cc',
               'pheap/pheap.cc',
               'pheap/vistaheap.c'	       
              ]

pool_user_sources = [
                     'pool/user/pool.cc'
                    ]

pool_kernel_sources = [
                       'pool/kernel/pool.cc',
                       'pool/kernel/buddy.cc'
                      ]

#lib_sources += pool_user_sources
lib_sources += pool_kernel_sources

scmLibrary = localBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)

localBuildEnv.Append(LIBS = ['pthread'])
localBuildEnv.Program(target = 'tool/pool/pool', source = lib_sources + ['tool/pool/main.cc', 'tool/pool/mkpool.cc'])

Return('scmLibrary')
