Import('buildEnv')
localBuildEnv = buildEnv.Clone()
scmLibraryBuildEnv = buildEnv.Clone()

lib_target = 'scm'

scm_sources = [
               'scm/model.cc',
               'scm/memcpy.cc',
              ]

pool_sources = [
                'pregion/pregion.cc',
                'pheap/pheap.cc',
                'pheap/vistaheap.c'	       
               ]

pool_user_sources = [
                     'pool/user/pool.cc'
                    ]

pool_kernel_sources = [
#                       'pool/kernel/pool-buddy.cc',
                       'pool/kernel/pool-vistaheap.cc',
                       'pool/kernel/buddy.cc'
                      ]

#pool_sources += pool_user_sources
pool_sources += pool_kernel_sources

scm_lib_objs = scmLibraryBuildEnv.Object(scm_sources)
pool_objs = scmLibraryBuildEnv.Object(pool_sources)
scmLibrary = scmLibraryBuildEnv.SharedLibrary(target = lib_target, source = scm_sources + pool_sources)

localBuildEnv.Append(LIBS = ['pthread'])
localBuildEnv.Program(target = 'tool/pool/pool', source = pool_objs + ['tool/pool/main.cc', 'tool/pool/mkpool.cc'])

Return('scmLibrary', 'scm_lib_objs')
