import os
import re
import sys
import string
import testfw
import copy
from integration_test import runIntegrationTests
#sys.path.append('%s/test/integration/osd' % (Dir('#').abspath))

Import('mainEnv', 'testEnv')
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('fssLibrary')
Import('mfsClientLibrary')
Import('mfsServerLibrary')
Import('commonLibrary')
Import('scmLibrary')
Import('bcsClientLibrary')
Import('bcsServerLibrary')
Import('osdClientLibrary')
Import('osdServerLibrary')
clientDepLibs = [mfsClientLibrary, fscLibrary, bcsClientLibrary, osdClientLibrary, scmLibrary, commonLibrary]
serverDepLibs = [mfsServerLibrary, fssLibrary, bcsServerLibrary, osdServerLibrary, scmLibrary, commonLibrary]
objects = myTestEnv['OBJECTS']

serverProgram = myTestEnv.Program('smain', \
	source = myTestEnv['SERVER_OBJECTS'], LIBS=['pthread', 'rt']+serverDepLibs)
testProgram = myTestEnv.Program('test', \
	source = [Glob('*.test.cc'), Glob('*.fixture.cc'), Glob('*.helper.cc'), \
                  Glob('*/*.test.cc'), Glob('*/*.fixture.cc'), Glob('*/*.helper.cc'), objects], \
	LIBS=['UnitTest++', 'pthread', 'rt']+clientDepLibs)
runtests = myTestEnv.Command("test.passed", ['test', fscLibrary], runIntegrationTests)



###############################################################################
# INTEGRATION TEST SCHEDULES
############################################################################### 



import test.integration.osd.lock
import test.integration.osd.hlock
import test.integration.osd.stm
import test.integration.osd.registry
import test.integration.osd.storage
import test.integration.osd.obj

test.integration.osd.lock.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.osd.hlock.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.osd.stm.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.osd.registry.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.osd.storage.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
test.integration.osd.obj.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
