Import('mainEnv')

rpcNetLibrary, rpcNetLibraryObjects = SConscript('rpc-net/SConscript')
rpcLibrary, rpcLibraryObjects = SConscript('rpc-fast/SConscript')

Return('rpcNetLibrary', 'rpcNetLibraryObjects', 'rpcLibrary', 'rpcLibraryObjects')
