Import('mainEnv')
Import('commonLibrary')

buildEnv = mainEnv.Clone()

buildEnv.Append(CPPPATH = ['#'])

lib_target = 'mfs'
lib_sources = ['radixtree.cc', 'hashtable.cc', 'finode.cc', 'mfs.cc', 'pinode.cc', 'sb.cc']
lib_sources += ['dinode.cc']
lib_sources += ['imgr.cc']

#mfsLibrary = buildEnv.StaticLibrary(target = lib_target, source = lib_sources)
mfsLibrary = buildEnv.SharedLibrary(target = lib_target, source = lib_sources)

#buildEnv.Program('main', ['main.cc', mfsLibrary, commonLibrary])

Return('mfsLibrary')


#C_SRC = Split("""
#              bio.c
#              file.c
#              fs.c
#              scm.c
#              spinlock.c
#	      sysfile.c
#              util.c
#              """)

#scmalloc_obj = Object('scmalloc.c')
#vistaheap_obj = Object('vistaheap.c')

#StaticLibrary('fs', C_SRC+[scmalloc_obj+vistaheap_obj], CCFLAGS='-g -fno-omit-frame-pointer')
#Program('main', ['main.c', 'libfs.a'], CCFLAGS='-g')
