Import('buildEnv')
Import('ipcClientLibrary')
Import('chunkstoreLibrary')
Import('lockservLibrary')
Import('commonLibrary')
Import('mfsClientLibrary')

localBuildEnv = buildEnv.Clone()
libLocalBuildEnv = buildEnv.Clone()

lib_target = 'fsc'
lib_sources = [
               'c_api.cc', 
               'client.cc', 
               'config.cc',
               'file.cc',
               'fsomgr.cc', 
	       'inode.cc',
               'mpinode.cc',
               'namespace.cc', 
	       '../dpo/main/client/dpo.cc',
               '../dpo/main/client/hlckmgr.cc',
               '../dpo/main/client/lckmgr.cc',
	       '../dpo/main/client/omgr.cc',
	       '../dpo/main/client/smgr.cc',
	       '../dpo/main/client/stm.cc',
	       '../dpo/main/client/registry.cc',
	       '../dpo/containers/name/container.cc',
	       '../dpo/containers/super/container.cc',
	       '../dpo/containers/byte/container.cc',
	       '../dpo/containers/set/container-client.cc',
	      ]
#libLocalBuildEnv.Append(LIBS = mfsClientLibrary)
#libLocalBuildEnv.Append(LIBS = ipcClientLibrary)
#libLocalBuildEnv.Append(LIBS = chunkstoreLibrary)
#libLocalBuildEnv.Append(LIBS = lockservLibrary)
#libLocalBuildEnv.Append(LIBS = commonLibrary)
#libLocalBuildEnv.Append(LIBS = ['pthread', 'rt'])
      
fscLibrary = libLocalBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)

# Be careful with linkage order for static libraries
localBuildEnv.Append(LIBS = mfsClientLibrary)
localBuildEnv.Append(LIBS = fscLibrary)
localBuildEnv.Append(LIBS = ipcClientLibrary)
localBuildEnv.Append(LIBS = chunkstoreLibrary)
localBuildEnv.Append(LIBS = lockservLibrary)
localBuildEnv.Append(LIBS = commonLibrary)
localBuildEnv.Append(LIBS = ['pthread', 'rt'])
localBuildEnv.Program('fsclient', ['main.cc']) 

Return('fscLibrary')
