Import('buildEnv')
Import('rpcLibrary')
Import('chunkstoreLibrary')
Import('lockservLibrary')
Import('commonLibrary')
Import('mfsLibrary')

localBuildEnv = buildEnv.Clone()
libLocalBuildEnv = buildEnv.Clone()

lib_target = 'fsc'
lib_sources = [
               'c_api.cc', 
               'client.cc', 
               'config.cc',
               'file.cc',
               'fsomgr.cc', 
	       'inode.cc',
               'mpinode.cc',
               'namespace.cc', 
	       'sb.cc',
               'smgr.cc',
               '../dpo/base/client/hlckmgr.cc',
               '../dpo/base/client/lckmgr.cc',
	       '../dpo/base/client/omgr.cc',
	       '../dpo/base/client/stm.cc',
	       '../dpo/containers/name/container.cc',
	       '../dpo/containers/super/container.cc'
	      ]
#libLocalBuildEnv.Append(LIBS = mfsLibrary)
#libLocalBuildEnv.Append(LIBS = rpcLibrary)
#libLocalBuildEnv.Append(LIBS = chunkstoreLibrary)
#libLocalBuildEnv.Append(LIBS = lockservLibrary)
#libLocalBuildEnv.Append(LIBS = commonLibrary)
#libLocalBuildEnv.Append(LIBS = ['pthread', 'rt'])
      
fscLibrary = libLocalBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)

# Be careful with linkage order for static libraries
localBuildEnv.Append(LIBS = mfsLibrary)
localBuildEnv.Append(LIBS = fscLibrary)
localBuildEnv.Append(LIBS = rpcLibrary)
localBuildEnv.Append(LIBS = chunkstoreLibrary)
localBuildEnv.Append(LIBS = lockservLibrary)
localBuildEnv.Append(LIBS = commonLibrary)
localBuildEnv.Append(LIBS = ['pthread', 'rt'])
localBuildEnv.Program('fsclient', ['main.cc']) 

Return('fscLibrary')
