Import('buildEnv')
localBuildEnv = buildEnv.Clone()

rpcLibrary, rpcLibraryObjects = SConscript('backend/SConscript')

# Client IPC layer

clt_lib_target = 'ipcclt'
clt_lib_objects = rpcLibraryObjects
clt_lib_sources = [
                   'main/client/ipc.cc'
                  ]

ipcClientLibrary = localBuildEnv.SharedLibrary(target = clt_lib_target, source = clt_lib_sources + clt_lib_objects)



# Server IPC layer

srv_lib_target = 'ipcsrv'
srv_lib_objects = rpcLibraryObjects
srv_lib_sources = [
		   'main/server/cltdsc.cc',
                   'main/server/ipc.cc',
                  ]

ipcServerLibrary = localBuildEnv.SharedLibrary(target = srv_lib_target, source = srv_lib_sources + srv_lib_objects)

Return('rpcLibrary', 'ipcClientLibrary', 'ipcServerLibrary')
