import os
import re
import sys
import string
import testfw
import copy
from integration_test import runIntegrationTests

Import('mainEnv', 'testEnv')
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('mfsLibrary')
Import('commonLibrary')
Import('chunkstoreLibrary')
Import('rpcLibrary')
Import('serverProgram')
depLibs = [mfsLibrary, fscLibrary, rpcLibrary, chunkstoreLibrary, commonLibrary]
objects = myTestEnv['OBJECTS']

testProgram = myTestEnv.Program('test', source = [Glob('*.test.cxx'), Glob('*.fixture.cxx'), Glob('*.helper.cxx'), objects], LIBS=['UnitTest++', 'pthread', 'rt']+depLibs)
runtests = myTestEnv.Command("test.passed", ['test', fscLibrary], runIntegrationTests)
testProgramAbspath = os.path.join(os.getcwd(), str(testProgram[0]))
serverProgramAbspath = str(serverProgram[0])


# Integration tests

test_list = [
             ('Lock', 'TestLockUnlockSingleClient1', 1),
             ('Lock', 'TestLockUnlockSingleClient2', 1),
             ('Lock', 'TestLockUnlockConcurrentClients1', 2),
             ('Lock', 'TestLockUnlockConcurrentClients2', 2),
             ('Lock', 'TestLockUnlockConcurrentClients3', 2),
             ('Lock', 'TestLockUnlockConcurrentClients4', 2),
             ('Lock', 'TestLockConvert1', 2),
             ('Lock', 'TestLockConvert2', 2),
             ('Lock', 'TestLockCancel1', 2),
             ('Lock', 'TestLockCancel2', 2),
             ('Lock', 'TestSharedLockUnlockConcurrentClients1', 2),
             ('Lock', 'TestSharedLockUnlockConcurrentClients2', 2),
             ('HLock', 'TestLockUnlockSingleClient1', 1),
             ('HLock', 'TestLockUnlockConcurrentClient1', 2),
             ('HLock', 'TestLockUnlockConcurrentClient2', 2),
	    ]


for test in test_list:
	suiteStr = test[0]
	testStr = test[1]
	numClients = test[2]
	test_obj = testfw.integration_test.IntegrationTest(suiteStr, testStr, timeout=5000)
	test_obj.setPreTest(testProgramAbspath, '-T,-init,-numclients=%d' % (numClients), {})
	test_obj.addTest(None, 'S', serverProgramAbspath, '-p 10000', {}, False)
	for i in range(numClients):
		test_obj.addTest(None, 'C%d' % (i+1), testProgramAbspath, '-T,-suite=%s,-test=%s,-host=10000' % (suiteStr, testStr), {})
	myTestEnv.addIntegrationTest(test_obj)
