Import('mainEnv')
Import('rpcLibrary')
Import('chunkstoreLibrary')
Import('lockservLibrary')
Import('commonLibrary')

buildEnv = mainEnv.Clone()


lib_target = 'fss'
lib_sources = ['nameservice.cc', 'registry.cc']

fssLibrary = buildEnv.StaticLibrary(target = lib_target, source = lib_sources)

buildEnv.Append(CPPPATH = ['#rpc', '#'])
buildEnv.Append(LIBS = fssLibrary)
buildEnv.Append(LIBS = rpcLibrary)
buildEnv.Append(LIBS = chunkstoreLibrary)
buildEnv.Append(LIBS = lockservLibrary)
buildEnv.Append(LIBS = commonLibrary)
buildEnv.Append(LIBS = ['pthread', 'rt'])
buildEnv.Program('fsserver', ['main.cc']) 
