Import('mainEnv')
Import('rpcLibrary')
Import('chunkstoreLibrary')
Import('lockservLibrary')
Import('commonLibrary')

buildEnv = mainEnv.Clone()


sources = [
           'lckmgr.cc',
           'main.cc',
           'namespace.cc'
          ]

buildEnv.Append(CPPPATH = ['#rpc', '#'])
buildEnv.Append(LIBS = rpcLibrary)
buildEnv.Append(LIBS = chunkstoreLibrary)
buildEnv.Append(LIBS = commonLibrary)
buildEnv.Append(LIBS = ['pthread', 'rt'])
buildEnv.Program('fsserver', sources) 
