
import os, sys
Import('mainEnv')

buildEnv = mainEnv.Clone()
buildEnv.Append(CPPDEFINES = ['-D__STDC_FORMAT_MACROS'])
buildEnv.Append(CPPPATH = ['#bench', '#src', '#'])
buildEnv.Append(LIBS = ['config'])

Import('cfscLibrary')
Import('rxfscLibrary')
Import('fscLibrary')
Import('mfsClientLibrary')
Import('commonLibrary')
Import('scmLibrary')
Import('bcsClientLibrary')
Import('osdClientLibrary')

osdClientDepLibs = [fscLibrary, mfsClientLibrary, bcsClientLibrary, osdClientLibrary, scmLibrary, commonLibrary]
vfsClientDepLibs = [fscLibrary, mfsClientLibrary, bcsClientLibrary, osdClientLibrary, scmLibrary, commonLibrary]
pxfsClientDepLibs = [fscLibrary, mfsClientLibrary, bcsClientLibrary, osdClientLibrary, scmLibrary, commonLibrary]
cfsClientDepLibs = [cfscLibrary, bcsClientLibrary, osdClientLibrary, scmLibrary, commonLibrary]
rxfsClientDepLibs = [rxfscLibrary, bcsClientLibrary, osdClientLibrary, scmLibrary, commonLibrary]

osdObject = SConscript('osd/SConscript')
vfsObject, pxfsObject, cfsObject, rxfsObject = SConscript('fs/SConscript')

commonObject = buildEnv.Object(['main.cc'])

osdUbenchProgram = buildEnv.Program('ubench_osd', commonObject + osdObject, LIBS=['pthread', 'rt'] + osdClientDepLibs)
vfsUbenchProgram = buildEnv.Program('ubench_vfs', commonObject + vfsObject, LIBS=['pthread', 'rt'] + vfsClientDepLibs)
pxfsUenchProgram = buildEnv.Program('ubench_pxfs', commonObject + pxfsObject, LIBS=['pthread', 'rt'] + pxfsClientDepLibs)
cfsUbenchProgram = buildEnv.Program('ubench_cfs', commonObject + cfsObject, LIBS=['pthread', 'rt'] + cfsClientDepLibs)
rxfsUbenchProgram = buildEnv.Program('ubench_rxfs', commonObject + rxfsObject, LIBS=['pthread', 'rt'] + rxfsClientDepLibs)
