import os, sys
Import('mainEnv')

buildEnv = mainEnv.Clone()
buildEnv.Append(CPPDEFINES = ['-D__STDC_FORMAT_MACROS'])
buildEnv.Append(CPPPATH = ['#src'])
buildEnv.Append(LIBS = ['config'])

Export('buildEnv')

rpcLibrary, bcsClientLibrary, bcsServerLibrary = SConscript('bcs/SConscript')
Export('rpcLibrary')
Export('bcsClientLibrary')
Export('bcsServerLibrary')
spaLibrary = SConscript('spa/SConscript')
Export('spaLibrary')
commonLibrary = SConscript('common/SConscript')
Export('commonLibrary')
ssaClientLibrary, ssaServerLibrary = SConscript('ssa/SConscript')
Export('ssaClientLibrary')
Export('ssaServerLibrary')
SConscript('pxfs/SConscript')
