Import('buildEnv')
Import('bcsServerLibrary')
Import('osdServerLibrary')
Import('scmLibrary')
Import('commonLibrary')
Import('mfsServerLibrary')

localBuildEnv = buildEnv.Clone()
libLocalBuildEnv = buildEnv.Clone()

lib_target = 'fss'
lib_sources = [
               'fs.cc',
               'server.cc',
	       'session.cc',
              ]

fssLibrary = libLocalBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)

localBuildEnv.Append(LIBS = fssLibrary)
localBuildEnv.Append(LIBS = bcsServerLibrary)
localBuildEnv.Append(LIBS = osdServerLibrary)
localBuildEnv.Append(LIBS = mfsServerLibrary)
localBuildEnv.Append(LIBS = scmLibrary)
localBuildEnv.Append(LIBS = commonLibrary)
localBuildEnv.Append(LIBS = ['pthread', 'rt'])
localBuildEnv.Program('fsserver', ['main.cc']) 

Return('fssLibrary')
