Import('buildEnv')
Import('ipcServerLibrary')
Import('spaLibrary')
Import('commonLibrary')
Import('mfsServerLibrary')

localBuildEnv = buildEnv.Clone()
libLocalBuildEnv = buildEnv.Clone()

lib_target = 'fss'
lib_sources = [
               '../ssa/main/server/ssa.cc',
               '../ssa/main/server/hlckmgr.cc',
               '../ssa/main/server/lckmgr.cc',
               '../ssa/main/server/salloc.cc',
               '../ssa/main/server/registry.cc',
               '../ssa/main/server/session.cc',
	       '../ssa/containers/name/container-server.cc',
               'fsmgr.cc',
               'namespace.cc',
               'server.cc',
	       'session.cc',
	       'sessionmgr.cc'
              ]

fssLibrary = libLocalBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)

localBuildEnv.Append(LIBS = fssLibrary)
localBuildEnv.Append(LIBS = ipcServerLibrary)
localBuildEnv.Append(LIBS = mfsServerLibrary)
localBuildEnv.Append(LIBS = spaLibrary)
localBuildEnv.Append(LIBS = commonLibrary)
localBuildEnv.Append(LIBS = ['pthread', 'rt'])
localBuildEnv.Program('fsserver', ['main.cc']) 

Return('fssLibrary')
