Import('buildEnv')
Import('ipcServerLibrary')
Import('salLibrary')
Import('commonLibrary')
Import('mfsServerLibrary')

localBuildEnv = buildEnv.Clone()
libLocalBuildEnv = buildEnv.Clone()

lib_target = 'fss'
lib_sources = [
               '../dpo/main/server/dpo.cc',
               '../dpo/main/server/hlckmgr.cc',
               '../dpo/main/server/lckmgr.cc',
               '../dpo/main/server/salloc.cc',
               '../dpo/main/server/registry.cc',
	       '../dpo/containers/set/container-server.cc',
               'fsmgr.cc',
               'namespace.cc',
               'server.cc',
              ]

fssLibrary = libLocalBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)

localBuildEnv.Append(LIBS = fssLibrary)
localBuildEnv.Append(LIBS = ipcServerLibrary)
localBuildEnv.Append(LIBS = mfsServerLibrary)
localBuildEnv.Append(LIBS = salLibrary)
localBuildEnv.Append(LIBS = commonLibrary)
localBuildEnv.Append(LIBS = ['pthread', 'rt'])
localBuildEnv.Program('fsserver', ['main.cc']) 

Return('fssLibrary')
