Import('buildEnv')
Import('scmLibrary')
Import('fssLibrary')
Import('bcsServerLibrary')
Import('osdServerLibrary')
Import('mfsServerLibrary')
Import('commonLibrary')


localBuildEnv = buildEnv.Clone()

sources = [
           'main.cc',
           'mkfs.cc',
          ]
localBuildEnv.Append(LIBS = fssLibrary)
localBuildEnv.Append(LIBS = bcsServerLibrary)
localBuildEnv.Append(LIBS = osdServerLibrary)
localBuildEnv.Append(LIBS = mfsServerLibrary)
localBuildEnv.Append(LIBS = scmLibrary)
localBuildEnv.Append(LIBS = commonLibrary)
localBuildEnv.Append(LIBS = ['pthread', 'rt'])
localBuildEnv.Program(target = 'pxfs', source = sources)
