Import('buildEnv')
localBuildEnv = buildEnv.Clone()
lib_sources = ['rpc.cc', 'connection.cc', 'pollmgr.cc', 'thr_pool.cc', 'jsl_log.cc']
lib_objects = localBuildEnv.SharedObject(lib_sources)
rpcLibrary = localBuildEnv.SharedLibrary('rpc', lib_objects)
Return('rpcLibrary', 'lib_objects')
