import os
import sys
import string
import testfw
import copy
from integration_test import runIntegrationTests

Import('mainEnv', 'testEnv')
myTestEnv = testEnv.Clone()

Import('fscLibrary')
Import('fssLibrary')
Import('mfsClientLibrary')
Import('mfsServerLibrary')
Import('commonLibrary')
Import('spaLibrary')
Import('ssaClientLibrary')
Import('ssaServerLibrary')
Import('ipcClientLibrary')
Import('ipcServerLibrary')
clientDepLibs = [mfsClientLibrary, fscLibrary, ipcClientLibrary, ssaClientLibrary, spaLibrary, commonLibrary]
serverDepLibs = [mfsServerLibrary, fssLibrary, ipcServerLibrary, ssaServerLibrary, spaLibrary, commonLibrary]
objects = myTestEnv['OBJECTS']

testProgram = myTestEnv.Program('test', source = [Glob('*.test.cc'), Glob('*.fixture.cc'), Glob('*.helper.cc'), objects], LIBS=['UnitTest++', 'pthread', 'rt']+clientDepLibs)
serverProgram = myTestEnv.Program('smain', source = ['smain.cc', 'ipc.handlers.cc'], LIBS=['pthread', 'rt']+serverDepLibs)
runtests = myTestEnv.Command("test.passed", ['test', fscLibrary], runIntegrationTests)


###############################################################################
# INTEGRATION TEST SCHEDULES
############################################################################### 


import test.integration.ipc.ipc
test.integration.ipc.ipc.addIntegrationTests(myTestEnv, Dir('#').abspath, testProgram, serverProgram)
