#ifndef __STAMNOS_KERNELMODE_SCMDISK_H
#define __STAMNOS_KERNELMODE_SCMDISK_H

#define SCMDISK_MAJOR                 240
#define SCMDISK_CONTROL_MAJOR         241

#define CONFIG_BLK_DEV_SCM_COUNT      1 
#define CONFIG_BLK_DEV_SCM_SIZE       8*1024*1024 /* KB */

#define SCMDISK_SET_SCM_BANDWIDTH     32002
#define SCMDISK_GET_SCM_BANDWIDTH     32003
#define SCMDISK_SET_DRAM_BANDWIDTH    32004
#define SCMDISK_GET_DRAM_BANDWIDTH    32005
#define SCMDISK_RESET_STATISTICS      32006
#define SCMDISK_PRINT_STATISTICS      32007


#endif /* __STAMNOS_KERNELMODE_SCMDISK_H */
