import os
import fnmatch
Import('mainEnv')


if GetOption('clean_tests') == True:
	matches = []
	for root, dirnames, filenames in os.walk('.'):
		for filename in fnmatch.filter(filenames, '*.passed'):
			matches.append(os.path.join(root, filename))
	for m in matches:
		os.remove(m)
	
if GetOption('test_print_debug') == True:
	mainEnv.Append(TEST_EXTRA_ARGS = '-d 5')

if GetOption('run_tests') == True:
	if mainEnv['TEST_FILTER'] is None:
		mainEnv['TEST_FILTER'] = ".*"
	SConscript('unit/SConscript') #, variant_dir = os.path.join('test', 'unit'))

if GetOption('run_integration_tests') == True:
	if mainEnv['TEST_FILTER'] is None:
		mainEnv['TEST_FILTER'] = ".*:.*"
	SConscript('integration/SConscript') #, variant_dir = s.path.join('test', 'integration'))


SConscript('interactive/SConscript') #, variant_dir = s.path.join('test', 'interactive'))
