import os
Import('mainEnv')

if GetOption('run_tests') == True:
	if mainEnv['TEST_FILTER'] is None:
		mainEnv['TEST_FILTER'] = ".*"
	SConscript('unit/SConscript') #, variant_dir = os.path.join('test', 'unit'))

if GetOption('run_integration_tests') == True:
	if mainEnv['TEST_FILTER'] is None:
		mainEnv['TEST_FILTER'] = ".*"
	SConscript('integration/SConscript') #, variant_dir = s.path.join('test', 'integration'))
