Import('buildEnv')

localBuildEnv = buildEnv.Clone()

lib_target = 'common'
lib_sources = ['config.c', 'hash.c', 'pheap.cc', 'vistaheap.c', 'debug.c', 'stack.c', 'rbt.c', 'interval_tree.cc']

localBuildEnv.Append(CPPPATH = ['#src/common'])

commonLibrary = localBuildEnv.SharedLibrary(target = lib_target, source = lib_sources)


Return('commonLibrary')
