Import('mainEnv')
Import('commonLibrary')

buildEnv = mainEnv.Clone()

buildEnv.Append(CPPPATH = ['#'])

lib_target = 'v6fs'
lib_sources = ['mkfs.cc', 'itree.cc']
v6fsLibrary = buildEnv.StaticLibrary(target = lib_target, source = lib_sources)

Return('v6fsLibrary')


#C_SRC = Split("""
#              bio.c
#              file.c
#              fs.c
#              scm.c
#              spinlock.c
#	      sysfile.c
#              util.c
#              """)

#scmalloc_obj = Object('scmalloc.c')
#vistaheap_obj = Object('vistaheap.c')

#StaticLibrary('fs', C_SRC+[scmalloc_obj+vistaheap_obj], CCFLAGS='-g -fno-omit-frame-pointer')
#Program('main', ['main.c', 'libfs.a'], CCFLAGS='-g')
